spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/springboot_aws
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always


spring.profiles.include: oauth

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace